export const stockSymbol: any = {
    'alphabet': 'GOOGL',
    'amazon': 'AMZN',
    'amd': 'AMD',
    'apple': 'AAPL',
    'bny mellon': 'BK',
    'dell': 'DELL',
    'disney': 'DIS',
    'facebook': 'FB',
    'google': 'GOOGL',
    'hp': 'HPQ',
    'ibm': 'IBM',
    'intel': 'INTC',
    'lyft': 'LYFT',
    'microsoft': 'MSFT',
    'netflix': 'NFLX',
    'nvidia': 'NVDA',
    'sony': 'SNE',
    'spotify': 'SPOT',
    'tesla': 'TSLA',
    'twitter': 'TWTR',
    'uber': 'UBER'
};